M48
; DRILL file {KiCad 9.0.3} date 2025-07-29T12:04:03-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-29T12:04:03-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X55.0Y-51.0
X55.0Y-137.0
X125.0Y-51.0
X125.0Y-137.0
M30
